require('dotenv').config();
require('./database');

const Genre = require('../models/genre');
const GameDescription = require('../models/gameDescription')
const Game = require('../models/game');

(async function() {

  await Genre.deleteMany({});
  const genres = await Genre.create([
    {name: 'adventure', sortOrder: 10},
    {name: 'action', sortOrder: 20},
    {name: 'rpg', sortOrder: 30},
    {name: 'horror', sortOrder: 40},
    {name: 'casual', sortOrder: 50}
  ]);

  await GameDescription.deleteMany({});
  const gameDescriptions = await GameDescription.create([
    {
      opening: 'Embark on an extraordinary co-op adventure in Forgotten Worlds, a thrilling tomb exploration game designed for up to four players. Delve into the enigmatic depths of ancient tombs, where untold treasures, mysterious puzzles, and perilous traps await. Team up with friends to uncover the secrets of long-forgotten civilizations, but beware the past holds both wonder and danger in this cooperative journey into the heart of exploration.',
      synopsis: 'Forgotten Worlds beckons you and your companions to unravel the mysteries concealed within ancient tombs, where the echoes of forgotten civilizations resonate through the hallowed halls. Form a team of up to four players, each with unique skills and abilities, and embark on a cooperative quest to unlock the secrets hidden beneath layers of history. The tombs are fraught with challenges, but with teamwork and cunning, the treasures of the Forgotten Worlds can be unearthed.',
      features: [`Cooperative Tomb Exploration: Join forces with up to three friends, either locally or online, to embark on an unforgettable cooperative journey. Teamwork is essential as you navigate complex puzzles, overcome traps, and face the challenges that lie within each forgotten tomb`,
      `Unique Character Roles: Choose from a diverse roster of explorers, each with their own specialized skills. Whether you're a nimble acrobat adept at traversing treacherous terrain, a historian with a knack for deciphering ancient scripts, or a skilled combatant ready to face supernatural threats, every character brings a unique contribution to the team.`,
      `Dynamic Puzzles and Traps: Encounter a variety of puzzles and traps that demand collaboration and strategic thinking. Solve riddles, activate ancient mechanisms, and overcome ingenious traps designed to protect the tombs' most guarded secrets. The journey into Forgotten Worlds is as much about wit as it is about skill.`,
      `Procedurally Generated Tombs: Explore an ever-changing landscape of tombs with procedurally generated layouts. No two expeditions are alike, ensuring a fresh and unpredictable experience with every playthrough. Adapt your strategies as the tombs reveal new challenges and mysteries.`,
      `Supernatural Adversaries: Uncover the supernatural forces that guard the forgotten treasures. Face off against spectral guardians, animated guardians, and otherworldly creatures that test your combat skills and demand cooperation to overcome.`,
      `Resource Management: Carefully manage your resources, from torches and grappling hooks to ancient artifacts, as you navigate the tombs. Cooperation is key in ensuring that your team has the tools necessary to brave the unknown and emerge victorious.`,
      `Captivating Environments: Immerse yourself in visually stunning tomb environments, from sprawling underground caverns to ancient temples bathed in ethereal light. The detailed landscapes enhance the atmosphere, making each tomb a living, breathing puzzle waiting to be unraveled.`,
      ],
      closing: `Forgotten Worlds invites you and your fellow explorers to embark on a cooperative journey through time and mystery. Will your team unveil the secrets hidden within the forgotten tombs, or will you become one with the mysteries that lie beneath? Gather your allies, gear up, and prepare to venture into the heart of exploration in Forgotten Worlds.`
    },
    {
      opening: `Embark on a heartwarming and whimsical adventure with Roscoe's Journey, a delightful platforming game that stars a charming cat on a quest to save his furry friends. Join Roscoe as he traverses vibrant landscapes, overcomes playful challenges, and discovers the magic of friendship in this adorable and enchanting journey.`,
      synopsis: `In Roscoe's Journey, you step into the furry paws of Roscoe, an adventurous cat whose peaceful world is suddenly disrupted when mischievous creatures snatch his feline friends. With boundless courage and a determination to rescue his companions, Roscoe sets out on a whimsical adventure filled with joy, discovery, and a dash of catnip-fueled mischief. Prepare to explore enchanting worlds, meet quirky characters, and experience the cutest platforming escapade ever!`,
      features: [`Adorable Platforming: Navigate charming levels filled with colorful obstacles and dynamic environments. Jump, climb, and sneak your way through whimsical landscapes that are as cute as they are challenging. Roscoe's Journey offers a perfect blend of accessible gameplay and platforming excitement for players of all ages.`,
      `Playful Puzzle Solving: Encounter delightful puzzles that require clever thinking and a touch of feline finesse. Whether it's stacking blocks, activating switches, or using Roscoe's unique abilities, each puzzle brings a sense of joy and accomplishment to the adventure.`,
      `Magical Abilities: Unleash Roscoe's magical cat abilities to overcome obstacles and outsmart enemies. Purr-fect your double-jump, perform graceful glides, and unleash a mesmerizing yarn ball attack to fend off foes. Discover new abilities as you progress, adding depth and variety to Roscoe's playful skill set.`,
      `Dynamic Friendships: Meet a cast of adorable characters on your journey, each with their own endearing personalities. Help them in charming side quests, and witness the magic of friendship as they join Roscoe on his quest. Together, they'll overcome challenges and create heartwarming memories.`,
      `Hidden Treasures: Explore secret nooks and crannies in each level to discover hidden treasures, collectible cat toys, and unlock adorable costumes for Roscoe. The more you explore, the more delightful surprises you'll find in this captivating world.`,
      `Lively Soundtrack: Immerse yourself in a cheerful and catchy soundtrack that complements the game's whimsical atmosphere. The music dynamically responds to Roscoe's actions, enhancing the joyous ambiance of the adventure.`,
      `Enchanting Visuals: Dive into a visually enchanting world where vibrant colors, charming character designs, and lively animations bring Roscoe's Journey to life. Every frame is a feast for the eyes, making each level a delightful playground for players to explore.`
      ],
      closing: `Roscoe's Journey invites you to join an adorable cat on a quest that's as heartwarming as it is entertaining. Will Roscoe rescue his furry friends and bring peace to his world? Embark on this paw-some adventure and discover the magic that awaits in Roscoe's charming world.`
    },
    {
      opening: `Embark on an emotional and heartwarming journey in Summit, an enchanting adventure game that follows the story of a young man on a quest to discover the true meaning of life. As he traverses breathtaking landscapes, encounters memorable characters, and faces life's trials, players will experience a captivating narrative filled with introspection, growth, and the beauty of human connections.`,
      synopsis: `In Summit, players step into the shoes of Alex, a young man seeking purpose and meaning in the midst of life's complexities. Set against the backdrop of stunning landscapes, from lush forests to snowy peaks, Summit unfolds as a soul-searching adventure. Alex's journey is not just about reaching the mountaintop; it's about discovering the profound lessons that lie along the way. Through trials and triumphs, players will witness the transformative power of human connections and the beauty that can be found in the smallest moments.`,
      features: [`Emotional Storytelling: Dive into a deeply emotional and relatable narrative that explores themes of self-discovery, friendship, and the pursuit of happiness. As Alex, players will navigate a journey of introspection and growth, facing challenges that resonate with the universal aspects of the human experience.`,
      `Breathtaking Environments: Explore visually stunning landscapes that reflect the changing seasons of Alex's life. From serene meadows to towering mountain peaks, each environment is a metaphorical chapter in Alex's story, offering both breathtaking beauty and moments of quiet reflection.`,
      `Character Relationships: Interact with a cast of memorable characters who shape Alex's journey. Through meaningful conversations and shared experiences, players will forge connections that evoke genuine emotions. These relationships play a pivotal role in Alex's growth, leaving a lasting impact on the unfolding narrative.`,
      `Puzzle Solving and Exploration: Encounter puzzles that mirror the challenges of life, each offering a chance for introspection and growth. Navigate through the landscape, uncover hidden paths, and solve puzzles that symbolize the obstacles faced on the journey to self-discovery.`,
      `Dynamic Weather and Day-Night Cycle: Experience a dynamic weather system and day-night cycle that influence the game's atmosphere. From calming sunsets to dramatic storms, the environment reflects Alex's emotional journey, creating a truly immersive and evocative experience.`,
      `Soulful Soundtrack: Immerse yourself in a soul-stirring soundtrack that complements the emotional highs and lows of Alex's journey. The music resonates with the themes of self-discovery and human connection, enhancing the emotional impact of the adventure.`,
      `Reflective Gameplay: Summit encourages players to pause, reflect, and appreciate the beauty of the journey. Whether it's taking in the scenic views or engaging in heartfelt conversations, the gameplay invites players to savor the moments that define Alex's path.`,
      ],
      closing: `Summit is more than a game; it's a poignant exploration of life's journey, with its peaks and valleys, joys and sorrows. Join Alex on this heartwarming adventure and discover the profound beauty that awaits at the Summit.`   
    },
    {
      opening: `Step into the hallowed shoes of a legendary samurai in Katana Sunset, an exhilarating action game that takes you on a visceral journey through feudal Japan. Master the art of the katana, confront deadly adversaries, and embrace the path of the warrior as you unravel a tale of honor, revenge, and the pursuit of inner peace against the breathtaking backdrop of a setting sun.`,
      synopsis: `Katana Sunset immerses players in the role of Hiroshi Kuroda, a seasoned samurai whose tranquil life is shattered by the betrayal of a once-loyal ally. Sworn to uphold justice and honor, Hiroshi embarks on a quest for vengeance that will take him across feudal Japan. As the sun sets on the horizon, the clash of steel echoes through the valleys, and a legendary warrior rises to confront the shadows that threaten to consume his world.`,
      features: [`Masterful Katana Combat: Wield the razor-sharp katana with precision and finesse, executing fluid and deadly combos. Each swing, parry, and strike is a dance of blades, allowing players to feel the weight and power of the iconic weapon as they engage in intense, fast-paced combat.`,
      `Dynamic Samurai Abilities: Unlock powerful samurai abilities that enhance your combat prowess. Harness the power of the elements, unleash devastating special attacks, and master the art of iaido for swift, lethal strikes. As Hiroshi, evolve into a true samurai legend with every battle.`,
      `Feudal Japan Exploration: Traverse beautifully rendered landscapes inspired by feudal Japan, from serene cherry blossom gardens to war-torn battlefields. Discover hidden paths, ancient shrines, and engage in breathtaking duels against both human foes and mythical adversaries.`,
      `Revenge-Driven Narrative: Unravel a gripping tale of betrayal, honor, and redemption as Hiroshi pursues those who have wronged him. Encounter memorable characters, make choices that shape the narrative, and face the consequences of your actions on the path to Katana Sunset's thrilling climax.`,
      `Strategic Enemy Encounters: Battle a diverse array of enemies, each with distinct fighting styles and abilities. Adapt your tactics to overcome hordes of foes, duel rival swordsmen, and face powerful bosses that demand skill, reflexes, and a deep understanding of samurai combat.`,
      `Zen-Inspired Art Style: Immerse yourself in an art style that blends traditional Japanese ink painting with modern game design. Katana Sunset's visual aesthetic captures the essence of feudal Japan, creating a visually stunning world that complements the intensity of the action.`,
      `Haunting Soundtrack: Immerse yourself in a haunting and atmospheric soundtrack that accompanies Hiroshi's journey. The music, steeped in traditional Japanese instrumentation, adds emotional depth to every strike, parry, and dramatic encounter.`
    ],
      closing: `Katana Sunset is not just a game; it's a symphony of steel, honor, and revenge set against the backdrop of a mesmerizing sunset. Will Hiroshi find redemption in the shadows, or will the path of the samurai lead him to a destiny bathed in the crimson hues of the setting sun? The answers await those who dare to walk the way of the sword in Katana Sunset.`
    },
    {
      opening: `Dive headfirst into the neon-soaked underworld of Ex Nihilo: Phantom Glitch, a gripping cyberpunk dystopian action game that thrusts you into a city on the brink of collapse. As an enigmatic hacker with a mysterious past, navigate the shadows, manipulate reality, and uncover the truth behind a phantom glitch that threatens to erase the very fabric of this dark, digital society.`,
      synopsis: `In the sprawling metropolis of Ex Nihilo, where the lines between reality and the digital realm blur, a phantom glitch is tearing at the seams of society. You play as Cipher, a renegade hacker with a shadowy past, armed with cybernetic enhancements and an insatiable thirst for the truth. As the city descends into chaos, you must navigate the twisted networks, manipulate reality itself, and confront the enigmatic forces behind the Phantom Glitch.`,
      features: [`Reality-Bending Hacking: Utilize cutting-edge hacking abilities to manipulate the digital and physical worlds. Hack into security systems, manipulate the environment, and unravel the city's secrets by bending reality to your will. The city is your playground, and every glitch in the system is a weapon at your disposal.`,
      `Dynamic Cybernetic Enhancements: Augment your body with cybernetic enhancements that grant you unparalleled abilities. Upgrade your neural interface, enhance reflexes, and install powerful hacking tools to become the ultimate digital warrior. Adapt your playstyle with customizable cybernetics that shape the way you approach each mission.`,
      `Fast-Paced Action: Immerse yourself in intense, fast-paced combat that seamlessly blends gunplay, hacking, and acrobatics. Engage in high-stakes firefights, execute precision takedowns, and use your hacking prowess to gain the upper hand against heavily augmented adversaries and corporate security forces.`,
      `Open-World Cyberpunk Dystopia: Explore a sprawling, open-world cityscape where the gleaming skyscrapers of corporate elites contrast with the gritty slums that house the city's downtrodden. Navigate dark alleyways, hackable billboards, and clandestine data centers as you uncover the interconnected threads of Ex Nihilo's corrupt society.`,
      `Intricate Storyline: Immerse yourself in a rich narrative woven with corporate intrigue, conspiracy, and the existential threat posed by the Phantom Glitch. Encounter a cast of morally ambiguous characters, each with their own motivations, as you untangle the web of deceit that shrouds the city.`,
      `Stylized Cyberpunk Aesthetic: Experience a visually stunning cyberpunk world inspired by retro-futurism and modern dystopian visions. Neon lights, holographic billboards, and rain-soaked streets create a mesmerizing backdrop for the dark and atmospheric narrative.`,
      `Synthetic Soundtrack: Immerse yourself in an electrifying synthetic soundtrack that echoes the pulsating rhythms of the cyberpunk underworld. The music adapts to the intensity of the action, enhancing the immersive experience of hacking, combat, and exploration.`
    ],
      closing: `Ex Nihilo: Phantom Glitch invites you to question reality, challenge authority, and carve your own path through the chaos of a cyberpunk dystopia. Will you unveil the truth hidden within the digital shadows, or become a phantom glitch in the corrupted code of Ex Nihilo? The fate of the city rests in your hands.`
    },
    {
      opening: `Step into the worn shoes of Rustin Gage, a grizzled detective with a chip on his shoulder and a score to settle in Rusted Gauge, a gritty urban noir action game that plunges players into the dark underbelly of a city rife with corruption and deception. Wrongfully framed and fueled by a thirst for justice, Gage is on a relentless quest to unravel the truth, bring the guilty to justice, and clear his tarnished name.`,
      synopsis: `In the shadowy corners of a city plagued by crime, Detective Rustin Gage once stood as a beacon of justice. However, a set-up framed him for a crime he didn't commit, leaving his reputation shattered and his career in ruins. Now, fueled by vengeance and armed with his own code of justice, Gage navigates the treacherous streets, unraveling a web of conspiracy that goes deeper than he could have ever imagined. Rusted Gauge is a tale of redemption, revenge, and the gritty pursuit of truth in a city that thrives on lies.`,
      features: [`Hard-Boiled Detective Action: Assume the role of Rustin Gage, a no-nonsense detective with a rugged demeanor and a knack for delivering justice. Engage in intense hand-to-hand combat, precise gunplay, and gritty investigations as you unravel the layers of corruption that infest the city.`,
      `City Underbelly Exploration: Navigate a meticulously crafted urban noir environment, from dimly lit alleys to smoke-filled bars and towering skyscrapers. Immerse yourself in the atmospheric, rain-soaked streets as you follow the twisted trail of betrayal and deceit.`,
      `Intense Combat System: Engage in visceral, hard-hitting combat that reflects Gage's streetwise brawling style. Chain together combos, disarm foes, and use the environment to your advantage in intense, close-quarters battles against both street thugs and corrupt law enforcement.`,
      `Conspiracies and Investigations: Piece together the puzzle of your own frame-up through gripping investigative sequences. Uncover hidden clues, interrogate suspects, and make moral decisions that impact the course of the narrative. The path to redemption is paved with deceit, and every choice matters.`,
      `Character-Driven Narrative: Immerse yourself in a narrative driven by morally ambiguous characters, each with their own motivations and secrets. Interact with a cast of individuals ranging from shady informants to former allies, as Gage digs deeper into the dark heart of the city.`,
      `Noir Visual Style: Experience a visually striking noir aesthetic that captures the essence of classic detective stories. Moody lighting, rain-soaked streets, and meticulous attention to detail create a cinematic experience that mirrors the gritty atmosphere of urban noir.`,
      `Jazzy, Atmospheric Soundtrack: Immerse yourself in a brooding, jazz-infused soundtrack that sets the tone for each gritty encounter and reflective moment. The music complements the noir atmosphere, enhancing the immersive narrative experience of Rusted Gauge.`
      ],
      closing: `Rusted Gauge invites you to step into the worn shoes of a detective wronged by the very system he once served. Will Gage unravel the conspiracy, expose the truth, and reclaim his tarnished legacy, or will he succumb to the shadows that threaten to consume him? The answers lie within the dark heart of the city, waiting to be uncovered in this gripping urban noir action game.`
    },
    {
      opening: `Embark on an enchanting journey with Homeward, a heartwarming and adorable fantasy role-playing game that follows the delightful adventures of a young girl named Lumi. After a whimsical mishap on her way home, Lumi finds herself lost in a magical world filled with friendly creatures and charming landscapes. Join her as she befriends fantastical companions, solves puzzles, and discovers the true meaning of home in this endearing tale of friendship and discovery.`,
      synopsis: `Homeward invites players to step into the shoes of Lumi, a cheerful young girl who, while on her way home, stumbles into a realm of magic and wonder. In this captivating world, Lumi encounters delightful creatures, from mischievous fairies to wise old owls, each eager to help her find her way back. Together with her newfound friends, Lumi embarks on a whimsical journey filled with laughter, camaraderie, and the magic of finding home in the most unexpected places.`,
      features: [`Enchanting Fantasy World: Explore vibrant and charming landscapes inspired by classic fairy tales, from mystical forests to sparkling meadows. Each area is a visual feast, teeming with magical creatures and hidden surprises that await Lumi and her companions.`,
      `Adorable Companions: Befriend an endearing cast of fantastical creatures, each with its own unique quirks and abilities. From the playful sprite who loves to dance to the gentle giant with a knack for gardening, Lumi's companions add joy and whimsy to her enchanting journey.`,
      `Puzzle-solving Adventures: Encounter delightful puzzles and challenges that require teamwork and creativity to solve. From interactive puzzles in ancient ruins to whimsical challenges set by curious creatures, Lumi's journey is filled with clever brain teasers that spark the imagination.`,
      `Heartwarming Narratives: Immerse yourself in a light-hearted and heartwarming narrative that unfolds as Lumi's bonds with her fantastical friends grow stronger. Discover the personal stories of the magical characters she meets, each contributing to the overarching theme of unity, kindness, and the magic of finding one's way home.`,
      `Magical Abilities: Unlock charming abilities as Lumi's journey progresses. Harness the power of magical artifacts, cast spells, and utilize the unique skills of her companions to overcome obstacles and unlock new areas of the enchanting world.`,
      `Customization and Collectibles: Personalize Lumi's appearance with adorable outfits and accessories discovered throughout her journey. Collect magical trinkets and hidden treasures that add a touch of whimsy to the adventure, and discover the stories behind each charming item.`,
      `Uplifting Soundtrack: Immerse yourself in an enchanting musical score that enhances the magical atmosphere of Lumi's journey. The uplifting melodies and cheerful tunes mirror the whimsical nature of the game, creating a delightful audio experience.`
      ],
      closing: `Homeward invites players of all ages to join Lumi on a charming quest through a fantastical world where friendship is the ultimate magic. Will Lumi find her way back home, or will the bonds she forms in this enchanting realm become the true treasure of her journey? Embark on this heartwarming adventure and let the magic unfold in Homeward.`
    },
    {
      opening: `Prepare to be transported to the enchanting realms of Oblivion Rainbow, a mesmerizing turn-based role-playing game that unfolds in a fantastical cosmic setting, adorned with eye-popping visuals that defy imagination. Embark on an otherworldly journey where vibrant colors, celestial landscapes, and strategic gameplay converge to create an immersive experience that transcends the boundaries of reality.`,
      synopsis: `In the cosmic tapestry of Oblivion Rainbow, the boundaries between dimensions blur, and the very fabric of reality becomes a canvas painted with the hues of the unimaginable. As a celestial wanderer, you find yourself thrust into a vibrant world where mystical creatures roam and cosmic energies pulse through the ether. The fate of the multiverse rests in your hands as you navigate the breathtaking landscapes, face formidable foes, and unveil the secrets hidden within the radiant spectrum.`,
      features: [`Surreal Cosmic Realms: Explore mesmerizing realms that defy conventional imagination, where floating islands of crystalline brilliance coexist with ethereal forests bathed in celestial glow. The cosmic landscapes of Oblivion Rainbow are a visual feast, offering a dazzling spectacle at every turn.`,
      `Strategic Turn-based Battles: Engage in strategic turn-based combat against celestial adversaries. Assemble a party of cosmic champions, each with unique abilities, and tactically command them to victory. Watch as vibrant spells and dazzling effects light up the cosmic battlefield in an ever-evolving dance of colors.`,
      `Celestial Companions: Recruit an eclectic cast of celestial companions, each embodying the essence of the cosmic realms. From astral mages channeling the energy of the stars to ethereal beings whose mere presence distorts reality, your companions contribute to the beauty and depth of the cosmic adventure.`,
      `Multiverse-spanning Quest: Embark on an epic quest that traverses diverse dimensions and uncovers the mysteries hidden within the Oblivion Rainbow. Encounter ancient cosmic beings, solve enigmatic puzzles, and make choices that ripple across the fabric of the multiverse, shaping the destiny of celestial realms.`,
      `Eye-popping Visuals: Immerse yourself in the spellbinding visuals of Oblivion Rainbow, where radiant colors blend seamlessly with cosmic landscapes. Witness the visual symphony unfold as you explore surreal environments, battle mystical creatures, and unlock the secrets of the cosmic tapestry.`,
      `Dimensional Puzzles: Confront mind-bending puzzles that challenge your perception and strategic thinking. Unlock hidden paths, manipulate cosmic energies, and solve puzzles that span the spectrum of the fantastical, adding an extra layer of depth to your cosmic journey.`,
      `Awe-inspiring Soundtrack: Immerse yourself in an awe-inspiring musical soundtrack that echoes the celestial grandeur of Oblivion Rainbow. From ethereal melodies to pulsating rhythms, the music complements the visual spectacle, creating an atmospheric symphony that resonates with the cosmic theme.`
      ],
      closing: `Oblivion Rainbow invites you to transcend the ordinary and embark on a cosmic adventure where vibrant visuals and strategic gameplay converge. Will you unlock the secrets of the radiant spectrum and restore cosmic harmony, or will the mysteries of Oblivion Rainbow remain veiled in celestial enchantment? Prepare to enter a realm where imagination knows no bounds and the cosmic journey awaits.`
    },
    {
      opening: `Sacrilege immerses players in a nightmarish tapestry of darkness, where salvation is a rare commodity and survival a fleeting hope. Face the malevolent forces that haunt the land, from cunning adversaries to colossal bosses, each harboring a power that echoes through the twisted corridors of despair.`,
      synopsis: `In the desolate realm of Sacrilege, where shadows cling to every corner and malevolence seeps through the very soil, you are thrust into a brutally unforgiving dark fantasy world. The echoes of forgotten legends and the wails of lost souls provide the ominous backdrop for your journey. Sacrilege is not a mere adventure—it's a test of resilience, a crucible of relentless challenges, punishing enemies, and epic boss encounters that will push you to the limits of your courage and skill.`,
      features: [`Unyielding Difficulty: Prepare for an arduous odyssey where death is not a setback but a stark reality. Enemies are merciless, their tactics cunning, and every battle demands the utmost skill, strategy, and precision. In Sacrilege, the line between victory and defeat is razor-thin.`,
      `Desolate Dark Fantasy World: Traverse a world marred by eternal night, where ghastly landscapes are cloaked in shadows, and ancient ruins whisper of untold horrors. Uncover the secrets of Sacrilege's past as you navigate treacherous terrain, haunted catacombs, and forsaken citadels.`,
      `Epic Boss Battles: Confront towering monstrosities and malevolent entities in epic encounters that test your mettle. Each boss is a formidable foe with unique abilities, requiring adaptability and mastery of combat skills. Only the boldest will emerge victorious from these awe-inspiring battles.`,
      `Classless Character Progression: Tailor your character's abilities without the confines of traditional classes. Experiment with diverse skill combinations, adapt your playstyle to the challenges at hand, and evolve into a formidable force against the ever-growing threats that loom in Sacrilege.`,
      `Lethal Weapons and Dark Arts: Arm yourself with a variety of lethal weapons, from razor-sharp blades to sinister magical arts. Each swing, each incantation must be executed with deadly precision as you face the relentless onslaught of the malevolent forces that seek to consume you.`,
      `Rich and Cryptic Lore: Uncover the twisted history that saturates Sacrilege. Decode ancient tomes, decipher cryptic inscriptions, and interact with enigmatic NPCs who may hold the keys to understanding the malevolence that plagues the land.`,
      `Dynamic Environments: Explore environments that react to your presence and actions. Solve intricate puzzles, discover hidden secrets, and navigate through perilous traps. Adaptability is the key to surviving the ever-shifting landscapes of Sacrilege.`,
      `Perilous Exploration: Embark on perilous journeys into the unknown, where darkness conceals unimaginable horrors and forbidden truths. Discover rare treasures and unravel the mysteries that deepen the narrative, but be prepared to face the consequences of your insatiable curiosity.`
      ],
      closing: `Sacrilege beckons the courageous, the unyielding, and those who dare to defy the encroaching darkness. Will you rise above the shadows, conquering the malevolence that shrouds Sacrilege, or will your soul become another lament in the symphony of despair? The trials are unforgiving, and the stakes are nothing short of your very existence. Enter the realm of Sacrilege, where the bravest shall be tested, and only the strongest will endure.`
    },
    {
      opening: `Prepare to descend into the infernal depths of Devil's Playground, a relentless action horror Metroidvania that thrusts you into the heart of Hell itself. As a damned soul seeking redemption, you must navigate treacherous landscapes, battle nightmarish demons, and unravel the mysteries of the underworld in this dark and atmospheric gaming experience.`,
      synopsis: `In Devil's Playground, you play as Damien, a tormented soul condemned to Hell for sins unknown. Tasked with a chance at redemption, you explore the nightmarish expanse of the underworld, battling demonic hordes and uncovering the sinister truths that bind your fate to the depths of damnation. Armed with supernatural abilities and a soul-stealing whip, you must confront the malevolent forces that dwell within Hell's twisted realms.`,
      features: [`Hellish Metroidvania Exploration: Traverse interconnected realms of Hell, from fiery pits to icy caverns, each teeming with demonic inhabitants and secrets waiting to be unveiled. Unleash your agility as you navigate labyrinthine environments, unlock new abilities, and uncover the interconnected pathways of Devil's Playground.`,
      `Intense Combat: Engage in visceral, fast-paced combat against a variety of demonic foes. Utilize a deadly array of weapons, including a soul-stealing whip that absorbs the essence of defeated enemies, empowering you with new abilities and enhancements. Adapt to the unique combat styles of each demon to survive the relentless onslaught.`,
      `Supernatural Abilities: Harness demonic powers bestowed upon you in Hell. Master teleportation, summon hellfire, and manipulate the very essence of your enemies. Customize your playstyle by choosing which abilities to enhance, creating a unique and powerful protagonist tailored to your preferences.`,
      `Monstrous Boss Battles: Confront colossal demonic entities that guard the darkest secrets of Hell. Each boss fight is a test of skill and strategy, pushing your limits as you face grotesque, otherworldly horrors determined to keep their dominion intact.`,
      `Gothic Atmosphere: Immerse yourself in a visually stunning, gothic aesthetic that captures the haunting beauty of Hell. From eerie landscapes to the grotesque designs of demonic creatures, every detail contributes to the oppressive and captivating atmosphere of Devil's Playground.`,
      `Non-linear Progression: Discover hidden paths, unlock shortcuts, and revisit previously inaccessible areas as you acquire new abilities and upgrades. The non-linear structure encourages exploration and rewards players who delve into the darkest corners of Hell.`,
      `Epic Soundtrack: Immerse yourself in an atmospheric and haunting soundtrack that amplifies the tension and intensity of your journey. The dynamic music adapts to your actions, heightening the sense of dread as you navigate the Devil's Playground.`
      ],
      closing: `Devil's Playground beckons you to confront your demons and navigate the twisted landscapes of Hell. Will you find redemption in the inferno, or succumb to the demonic forces that lurk within? The journey through the depths of damnation awaits those brave enough to step into this action-packed horror Metroidvania.`
    },
    {
      opening: `Prepare to unravel the haunting legacy of the past in Quiet Plateau: Sins of the Father, a chilling psychological horror game set within the confines of a desolate mansion. As a haunted protagonist with a dark family history, you must navigate the eerie halls, solve enigmatic puzzles, and confront the malevolent entities that thrive on the unsettling secrets hidden within the walls.`,
      synopsis: `In Quiet Plateau: Sins of the Father, you assume the role of Samuel Holt, a tormented individual drawn to his family's ancestral home, the foreboding Hawthorn Manor. Shrouded in mystery and perched atop a desolate plateau, the mansion holds the keys to Samuel's traumatic past. As you delve into the macabre depths of the estate, the sins of generations past come to life, and the boundaries between guilt, redemption, and horror blur.`,
      features: [`Immersive Exploration: Navigate the shadowy corridors and forgotten chambers of Hawthorn Manor, each room echoing with the weight of a family's sins. Uncover hidden passages, solve intricate puzzles, and unveil the horrifying truth that lies dormant within the mansion's walls.`,
      `Psychological Torment: The quiet plateau conceals a web of psychological torment. Encounters with spectral apparitions and nightmarish manifestations challenge your grip on reality. Your character's mental state is fragile, and the choices you make will determine whether you can endure the relentless assault on your sanity.`,
      `Dark Family Secrets: Discover the harrowing secrets that have plagued the Holt family for generations. As Samuel, you must confront the sins of your father and decipher cryptic clues scattered throughout the mansion, all while avoiding the vengeful entities that guard the dark truths hidden within Hawthorn Manor.`,
      `Dynamic Fear Mechanics: The malevolent presence within the house responds to your actions and choices, adapting to exploit your deepest fears and darkest regrets. The more you uncover, the more the haunting entities intensify, creating an ever-evolving atmosphere of dread.`,
      `Enigmatic Puzzles: Solve intricate puzzles that bridge the gap between the mansion's physical and supernatural realms. Each puzzle piece unravels a fragment of the unsettling history, leading you deeper into the heart of the horror that has gripped the Holt family for centuries.`,
      `Haunting Audio Design: The eerie echoes of the mansion, the unsettling whispers of forgotten sins, and the haunting musical score work in tandem to immerse you in the unsettling atmosphere of Quiet Plateau. The dynamic audio design heightens the suspense, ensuring a bone-chilling experience with every step.`,
      `Non-linear Storyline: Shape Samuel's fate through your choices, with multiple branching paths that lead to different endings. Can you break the cycle of familial horror, or will you succumb to the sins of the father and become another tortured soul haunting the halls of Hawthorn Manor?`
      ],
      closing: `Quiet Plateau: Sins of the Father invites you to confront the darkest corners of the human psyche, where family secrets intertwine with supernatural horrors. Will you uncover the truth and free yourself from the haunting legacy, or become another victim of the malevolent forces that linger within the silent halls of Hawthorn Manor? The answers lie within the unsettling tapestry of this psychological horror experience.`
    },
    {
      opening: `Prepare to venture into the nightmarish depths of a child's imagination in Traumatica: Whispers of the Innocent, a haunting horror experience that thrusts players into the eerie journey of a young girl named Emily. As she navigates a realm where her fears take shape as malevolent monsters, the lines between reality and nightmare begin to blur in this spine-chilling video game.`,
      synopsis: `Traumatica: Whispers of the Innocent introduces players to Emily, a courageous but terrified young girl who awakens in a surreal world fueled by her deepest fears. As the boundary between dreams and reality fades, Emily must confront monstrous entities born from her imagination, all while unraveling the mysteries that bind her to this distorted dimension. Armed only with a flickering lantern and her wits, players guide Emily through the twisted landscapes of her own subconscious.`,
      features: [`Childhood Vulnerability: Experience the world through the innocent eyes of Emily, a child who must face the twisted manifestations of her fears. Witness the clash between the fragile nature of youth and the monstrous entities that roam the haunting landscapes.`,
      `Dynamic Fear Mechanism: Emily's fear is a tangible force that influences the environment and the behavior of the monsters. Manage her emotions carefully, as heightened fear levels can distort reality and make encounters with the nightmarish creatures even more perilous.`,
      `Monstrous Puzzles: Confront puzzles that intertwine with the fearsome nature of the realm. Each challenge reflects the enigmatic complexity of a child's imagination, requiring a blend of creativity and resilience to overcome.`,
      `Unique Monster Encounters: Encounter a variety of monsters, each representing a different facet of Emily's fears. Develop strategies to outsmart, distract, or even befriend these creatures as you progress through the eerie landscapes.`,
      `Evolving Relationships: Forge connections with certain monsters that may aid or hinder Emily based on your choices throughout the game. The emotional dynamics between the young girl and the monsters add layers of depth to the narrative.`,
      `Nightmarish Environments: Traverse through eerie and atmospheric environments that seamlessly transition from whimsical to terrifying. From forgotten playgrounds to shadow-laden bedrooms, every location serves as a canvas for the nightmares lurking within Emily's subconscious.`,
      `Spellbinding Soundtrack: Immerse yourself in a hauntingly beautiful soundtrack that mirrors the emotional journey of a child's fears. The music adapts to the intensity of the encounters, enhancing the suspense and immersion throughout the game.`
      ],
      closing: `Traumatica: Whispers of the Innocent is a chilling exploration of the delicate balance between a child's innocence and the monstrous entities born from imagination. Will Emily conquer the shadows within her mind, or will she succumb to the nightmarish whispers that threaten to consume her very essence? The answers await within the unsettling realms of Traumatica.`
    },
    {
      opening: `Ball Boy Mania! invites players to experience the joy and excitement of tennis through the eyes of Max, a spirited young ball boy with a passion for the game. As Max, your mission is to keep the tennis matches running smoothly, collecting and delivering tennis balls with flair and style. The game is a celebration of tennis, friendship, and the boundless enthusiasm of youth.`,
      synopsis: `Welcome to the heartwarming world of Ball Boy Mania!, where you step into the sneakers of Max, an energetic young boy with dreams as big as a tennis court. Join Max as he embarks on a charming adventure as the newest ball boy sensation, navigating the lively and exhilarating world of tennis matches. With quick reflexes, playful challenges, and an infectious spirit, Max is set to steal hearts and create a tennis experience like no other in Ball Boy Mania!`,
      features: [`Courtside Adventures: Step onto vibrant tennis courts, each with its own unique atmosphere, from classic grassy lawns to bustling urban arenas. Immerse yourself in the energetic world of tennis, complete with cheering crowds, dynamic matches, and iconic tennis stars.`,
      `Playful Ball Boy Tasks: Take control of Max as he dashes across the court, collecting tennis balls and ensuring that the players are always ready for action. Max's playful animations and charming antics add a delightful touch to the courtside experience.`,
      `Tennis Matches Galore: Experience a variety of tennis matches, ranging from friendly exhibitions to intense championship battles. Your role as Max is crucial in maintaining the flow of the match, contributing to the overall success of the players and the enjoyment of the crowd.`,
      `Quick Reflex Challenges: Test your reflexes in entertaining mini-games that simulate the fast-paced nature of being a ball boy. Dodge obstacles, catch balls with precision, and navigate the court with agility. Mastering these challenges not only keeps the game going but also unlocks fun rewards for Max.`,
      `Dynamic Tennis Stars: Interact with a diverse cast of charming tennis players, each with their own unique personality and playing style. Engage in lighthearted banter, witness impressive on-court skills, and build friendships as Max becomes a beloved figure among the tennis stars.`,
      `Customization and Upgrades: Personalize Max's appearance and improve his skills as you progress through the game. Unlock a variety of quirky outfits, earn new equipment, and enhance Max's abilities to make him a true ball boy sensation.`,
      `Joyful Crowd Reactions: Feel the energy of the crowd as you perform exceptional moves during matches. Cheerful applause, supportive cheers, and even special crowd interactions create a lively atmosphere that celebrates Max's integral role in the tennis spectacle.`,
      `Uplifting Soundtrack: Groove to an uplifting and catchy soundtrack that complements the joyful nature of Max's adventures. The music adds an extra layer of positivity to the game, creating a feel-good atmosphere for players of all ages.`
      ],
      closing: `Ball Boy Mania! is not just a game; it's an invitation to join Max on a tennis adventure filled with fun, friendship, and courtside charm. Will Max become the ultimate ball boy sensation, or will he face unexpected challenges on his path to tennis stardom? Get ready to embark on a journey where every tennis match is a celebration, and the spirit of youth shines brightly in Ball Boy Mania!`
    },
    {
      opening: `Tax Audit Simulator places you in the shoes of an ordinary taxpayer thrust into the midst of a tax audit. Your financial decisions, deductions, and record-keeping are under the scrutinizing gaze of auditors, and it's up to you to ensure that every aspect of your financial life is above board. With realistic scenarios, challenging decisions, and potential pitfalls, Tax Audit Simulator is an immersive experience that tests your financial acumen and strategic thinking.`,
      synopsis: `Embark on a thrilling journey through the intricate world of tax compliance in Tax Audit Simulator. As a taxpayer facing the daunting prospect of an audit, you must navigate the complexities of financial scrutiny, make strategic decisions, and employ shrewd tactics to prevent yourself from getting into trouble with the tax authorities. Will you emerge unscathed, or will you succumb to the challenges of financial scrutiny in this high-stakes simulation?`,
      features: [`Audit Preparation: Dive into the meticulous process of preparing for a tax audit. Review financial documents, organize receipts, and ensure that your records are impeccable. Your attention to detail in this phase will play a crucial role in the outcome of the audit.`,
      `Decision-making Dilemmas: Navigate through a series of decisions during the audit process. From responding to auditor queries to deciding on the legitimacy of deductions, every choice you make influences the audit's outcome. Will you choose transparency, negotiation, or clever evasion?`,
      `Strategic Tactics: Employ a range of tactics to prevent yourself from getting into trouble. Engage in discussions with auditors, present well-documented evidence, and strategically choose when to cooperate or contest findings. Craft a strategy that aligns with your financial situation and the nuances of tax laws.`,
      `Legal Maneuvers: Explore legal avenues to safeguard your financial interests. Seek the advice of tax professionals, engage in settlement negotiations, and consider legal defenses if disputes arise. Balancing legal compliance with strategic maneuvers is key to navigating the audit successfully.`,
      `Financial Management: Manage your finances wisely to avoid audit triggers and maintain a clean financial record. Track income and expenses, understand tax regulations, and make informed financial decisions to minimize the risk of getting flagged for an audit.`,
      `Random Events: Encounter unexpected challenges and random events that can influence the audit process. From changes in tax laws to surprise audits, adaptability is crucial in ensuring a successful outcome.`,
      `Reputation Management: Guard your financial reputation throughout the simulation. Every decision you make, every document you submit, and every interaction with auditors contributes to your overall standing. A positive reputation may open doors, while a negative one could lead to further scrutiny.`,
      `Multiple Endings: Experience different outcomes based on your decisions and financial choices. Successfully navigate the audit and emerge unscathed, or face the consequences of a poorly managed financial situation. Your journey through Tax Audit Simulator is a reflection of your financial prowess.`
      ],
      closing: `Tax Audit Simulator is more than just a game—it's a strategic exploration of financial responsibility, decision-making, and the nuances of tax compliance. Will you emerge from the audit unharmed, or will you face the repercussions of financial missteps? Get ready for a high-stakes simulation that challenges your financial wits and tests your ability to navigate the intricate world of tax audits.`
    },
    {
      opening: `In Bubble Buddy, players are introduced to an enchanting world where bubbles come to life, and you have the opportunity to befriend a bubbly companion like no other. Meet your lively Bubble Buddy, a cheerful and animated bubble ready to share moments of joy and laughter with you. Your mission is simple: take care of your Bubble Buddy and enjoy a range of delightful activities together.`,
      synopsis: `Embark on a heartwarming journey of friendship and care in Bubble Buddy, a casual game that invites players to embrace the joy of companionship with the most delightful and carefree companion—a sentient bubble! Nurture your Bubble Buddy, engage in whimsical activities, and explore a world filled with laughter and simple pleasures. It's time to experience the joy of a unique and bubbly friendship in this charming casual game.`,
      features: [`Adopt Your Bubble Buddy: Meet your charming Bubble Buddy and watch as it responds to your interactions with lively animations and playful expressions. Customize your Bubble Buddy with fun accessories and colors to make it uniquely yours.`,
      `Nurture and Care: Take care of your Bubble Buddy by providing it with the care it needs to stay happy and vibrant. Feed it bubbles, play gentle games, and create a harmonious environment to ensure your Bubble Buddy is in high spirits.`,
      `Playful Activities: Engage in a variety of entertaining activities with your Bubble Buddy. Play bubble tag, create bubble art, or simply enjoy a serene float across the screen. Discover new games and pastimes that will keep both you and your Bubble Buddy entertained.`,
      `Bubble World Exploration: Explore a captivating world filled with vibrant colors and enchanting landscapes. Journey through bubble-filled meadows, serene skies, and shimmering lakes as you discover new areas to play and bond with your Bubble Buddy.`,
      `Charming Interactions: Interact with your Bubble Buddy using intuitive touch controls that allow you to tap, pop, and guide your companion through the whimsical world. The responsive and delightful interactions enhance the immersive experience of caring for your bubbly friend.`,
      `Friendship Meter: Build a strong bond with your Bubble Buddy and watch as the friendship meter grows with each shared moment. The stronger your connection, the more playful and affectionate your Bubble Buddy becomes.`,
      `Dynamic Weather: Experience dynamic weather changes that influence the mood and activities in the bubble world. Enjoy sunny days, gentle rain showers, and sparkling starlit nights as you create beautiful memories with your Bubble Buddy.`,
      `Relaxing Soundtrack: Immerse yourself in a soothing and uplifting soundtrack that complements the serene atmosphere of Bubble Buddy. The melodic tunes enhance the overall experience, creating a delightful ambiance for you and your bubbly friend.`
      ],
      closing: `Bubble Buddy is not just a game; it's a delightful celebration of companionship, laughter, and the simple joys of friendship. Join your Bubble Buddy on a carefree journey, and let the bubbles of joy and happiness surround you in this charming casual game.`
    }
  ])


  await Game.deleteMany({});
  const games = await Game.create([
    {name: 'Forgotten Worlds', image: 'https://i.imgur.com/q8vinEn.png', description: gameDescriptions[0], genre: genres[0], price: 19.99},
    {name: `Roscoe's Journey`, image: 'https://i.imgur.com/H3UFVnx.png', description: gameDescriptions[1], genre: genres[0], price: 9.99},
    {name: 'Summit', image: 'https://i.imgur.com/LuoI5ks.png', description: gameDescriptions[2], genre: genres[0], price: 19.99},
    {name: 'Katana Sunset', image: 'https://i.imgur.com/XYMibD6.png', description: gameDescriptions[3], genre: genres[1], price: 34.99},
    {name: 'Ex Nihilo: Phantom Glitch', image: 'https://i.imgur.com/2RUWBP0.png', description: gameDescriptions[4], genre: genres[1], price: 29.99},
    {name: 'Rusted Gauge', image: 'https://i.imgur.com/NGIoaZg.png', description: gameDescriptions[5], genre: genres[1], price: 24.99},
    {name: 'Homeward', image: 'https://i.imgur.com/6jfml9K.png', description: gameDescriptions[6], genre: genres[2], price: 19.99},
    {name: 'Oblivion Rainbow', image: 'https://i.imgur.com/xzcadap.png', description: gameDescriptions[7], genre: genres[2], price: 29.99},
    {name: 'Sacrilege', image: 'https://i.imgur.com/imn6vDY.png', description: gameDescriptions[8], genre: genres[2], price: 39.99},
    {name: `Devil's Playground`, image: 'https://i.imgur.com/BgZLuiW.png', description: gameDescriptions[9], genre: genres[3], price: 29.99},
    {name: 'Quiet Plateau: Sins of the Father', image: 'https://i.imgur.com/oOyKd8A.png', description: gameDescriptions[10], genre: genres[3], price: 19.99},
    {name: 'Traumatica', image: 'https://i.imgur.com/ZW9vfJF.png', description: gameDescriptions[11], genre: genres[3], price: 14.99},
    {name: 'Ball Boy Mania!', image: 'https://i.imgur.com/YBC1vCk.png', description: gameDescriptions[12], genre: genres[4], price: 4.99},
    {name: 'Tax Audit Simulator', image: 'https://i.imgur.com/vFhuJZA.png', description: gameDescriptions[13], genre: genres[4], price: 14.99},
    {name: 'Bubble Buddy', image: 'https://i.imgur.com/3C1Ablh.png', description: gameDescriptions[14], genre: genres[4], price: 9.99},

  ]);

  console.log(games)

  process.exit();

})();

